// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    // Test name: login
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/login | 
    await driver.get("http://localhost:3000/login")
    // 2 | setWindowSize | 1440x817 | 
    await driver.manage().window().setRect({ width: 1440, height: 817 })
    // 3 | type | name=nickname | jose.obatista@souunit.com.br
    await driver.findElement(By.name("nickname")).sendKeys("jose.obatista@souunit.com.br")
    // 4 | type | name=password | 12345
    await driver.findElement(By.name("password")).sendKeys("12345")
    // 5 | click | name=nickname | 
    await driver.findElement(By.name("nickname")).click()
    // 6 | type | name=nickname | osmariojr
    await driver.findElement(By.name("nickname")).sendKeys("osmariojr")
    // 7 | type | name=password | 12345678
    await driver.findElement(By.name("password")).sendKeys("12345678")
    // 8 | click | id=botao | 
    await driver.findElement(By.id("botao")).click()
  })
})
